import sqlite3
import os
from pathlib import Path
from autogameplayer.core.config import settings

def cleanup():
    print("🧹 Cleaning up bad data generated by synchronization issues...")
    
    # 1. Clear Explored Locations (Spatial Memory)
    db_path = settings.base_dir / "data" / "knowledge" / "world_map.db"
    if db_path.exists():
        try:
            conn = sqlite3.connect(str(db_path))
            conn.execute("DELETE FROM explored_locations")
            conn.commit()
            conn.close()
            print("✅ Cleared spatial memory (explored_locations). AI will re-map the world accurately.")
        except Exception as e:
            print(f"⚠️ Failed to clear spatial DB: {e}")

    # 2. Identify and Remove Broken TAS recordings (Tick 0 bug)
    datasets_dir = settings.datasets_dir
    if datasets_dir.exists():
        removed_count = 0
        import json
        for file in datasets_dir.glob("*.json"):
            try:
                with open(file, "r") as f:
                    data = json.load(f)
                    events = data.get("events", [])
                    # If most events are at tick 0, it's a broken recording
                    if len(events) > 5 and all(e.get("tick") == 0 for e in events[:5]):
                        os.remove(file)
                        removed_count += 1
            except Exception:
                pass
        print(f"✅ Removed {removed_count} broken TAS recordings with zero-tick timing.")

    # 3. Penalize current skills so they are re-validated
    # We don't delete them, but we set reliability low so the AI re-tests them
    skills_db = settings.base_dir / "data" / "knowledge" / "skills.db"
    if skills_db.exists():
        try:
            conn = sqlite3.connect(str(skills_db))
            conn.execute("UPDATE skills SET reliability = 0.5")
            conn.commit()
            conn.close()
            print("✅ Reset skill reliability. Macros will be re-validated with the new sync logic.")
        except Exception as e:
            print(f"⚠️ Failed to reset skills: {e}")

    print("\n✨ Cleanup complete. The AI will now generate high-fidelity data.")

if __name__ == "__main__":
    cleanup()
